/**
 * A GUI implementation of blackjack in Swing for ITE-6102 final
 * 
 * @author Joshua Timothy E. Abad
 */

package blackjack;

import blackjack.design.Format;
import blackjack.design.ImageResizer;
import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

public class AutoView extends javax.swing.JFrame {

    private JLabel[] playerHand;
    private JLabel[] dealerHand;
    private HashMap<String, JButton> playOptions;
    private JButton[] betOptions;
    private HashMap<String, JButton> handOptions;

    private final String FONT_NAME;

    /**
     * Creates new form BlackjackGUI
     */
    @SuppressWarnings("unchecked")
    public AutoView() {
        initComponents();
        initView();
        FONT_NAME = "Segoe UI";
    }

    private void initView() {
        playerHand = new JLabel[11];
        playerHand[0] = playerCardLabel1;
        playerHand[1] = playerCardLabel2;
        playerHand[2] = playerCardLabel3;
        playerHand[3] = playerCardLabel4;
        playerHand[4] = playerCardLabel5;
        playerHand[5] = playerCardLabel6;
        playerHand[6] = playerCardLabel7;
        playerHand[7] = playerCardLabel8;
        playerHand[8] = playerCardLabel9;
        playerHand[9] = playerCardLabel10;
        playerHand[10] = playerCardLabel11;

        dealerHand = new JLabel[11];
        dealerHand[0] = dealerCardLabel1;
        dealerHand[1] = dealerCardLabel2;
        dealerHand[2] = dealerCardLabel3;
        dealerHand[3] = dealerCardLabel4;
        dealerHand[4] = dealerCardLabel5;
        dealerHand[5] = dealerCardLabel6;
        dealerHand[6] = dealerCardLabel7;
        dealerHand[7] = dealerCardLabel8;
        dealerHand[8] = dealerCardLabel9;
        dealerHand[9] = dealerCardLabel10;
        dealerHand[10] = dealerCardLabel11;

        for (int i = 0; i < 11; i++) {
            playerHand[i].setText("");
            dealerHand[i].setText("");
        }
        
        titleLabel.setText("");
        titleLabel.setIcon(ImageResizer.getScaledImage(
                new ImageIcon(getClass().getResource(
                        "/blackjack/images/logo1.png"
                )),
                150
        ));

        chipsLabel.setForeground(Color.WHITE);
        chipsLabel.setFont(new Font(FONT_NAME, 0, 36));
        chipsLabel.setIcon(ImageResizer.getScaledImage(
                new ImageIcon(getClass().getResource(
                        "/blackjack/images/chip.png"
                )),
                chipsLabel.getFont().getSize()
        ));

        playOptions = new HashMap<>();
        playOptions.put("Hit", hitButton);
        playOptions.put("Stand", standButton);
        playOptions.put("Double Down", doubleDownButton);
        playOptions.put("Surrender", surrenderButton);

        betOptions = new JButton[5];
        betOptions[0] = betButton1;
        betOptions[1] = betButton2;
        betOptions[2] = betButton3;
        betOptions[3] = betButton4;
        betOptions[4] = betButton5;

        handOptions = new HashMap<>();
        handOptions.put("Deal", dealButton);
        handOptions.put("Next Hand", nextHandButton);
        handOptions.put("Quit Game", quitGameButton);

        getContentPane().setBackground(tablePanel.getBackground().darker());
        currentBetPanel.setBackground(
                getContentPane().getBackground().darker()
        );
        betOptionsPanel.setBackground(
                getContentPane().getBackground().darker()
        );
        playOptionsPanel.setBackground(
                getContentPane().getBackground().darker()
        );
        handOptionsPanel.setBackground(
                getContentPane().getBackground().darker()
        );
        playOptions.values().forEach((playOption) -> {
            playOption.setBackground(playOptionsPanel.getBackground().darker());
        });
        handOptions.values().forEach((handOption) -> {
            handOption.setBackground(handOptionsPanel.getBackground().darker());
        });

        clearHandValue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        betOptionsPanel = new JPanel();
        betButton1 = new JButton();
        betButton2 = new JButton();
        betButton3 = new JButton();
        betButton4 = new JButton();
        betOptionsLabel = new JLabel();
        betButton5 = new JButton();
        currentBetPanel = new JPanel();
        currentBetValueLabel = new JLabel();
        currentBetLabel = new JLabel();
        tablePanel = new JPanel();
        titleLabel = new JLabel();
        dealerPanel = new JPanel();
        dealerCardLabel1 = new JLabel();
        dealerCardLabel2 = new JLabel();
        dealerCardLabel3 = new JLabel();
        dealerCardLabel4 = new JLabel();
        dealerCardLabel5 = new JLabel();
        dealerCardLabel6 = new JLabel();
        dealerCardLabel7 = new JLabel();
        dealerCardLabel8 = new JLabel();
        dealerCardLabel9 = new JLabel();
        dealerCardLabel10 = new JLabel();
        dealerCardLabel11 = new JLabel();
        dealerHandValueLabel = new JLabel();
        chipsLabel = new JLabel();
        playerPanel = new JPanel();
        playerCardLabel1 = new JLabel();
        playerCardLabel2 = new JLabel();
        playerCardLabel3 = new JLabel();
        playerCardLabel4 = new JLabel();
        playerCardLabel5 = new JLabel();
        playerCardLabel6 = new JLabel();
        playerCardLabel7 = new JLabel();
        playerCardLabel8 = new JLabel();
        playerCardLabel9 = new JLabel();
        playerCardLabel10 = new JLabel();
        playerCardLabel11 = new JLabel();
        playerHandValueLabel = new JLabel();
        messagePanel = new JPanel();
        messageLabel = new JLabel();
        playOptionsPanel = new JPanel();
        hitButton = new JButton();
        standButton = new JButton();
        surrenderButton = new JButton();
        doubleDownButton = new JButton();
        playOptionsLabel = new JLabel();
        handOptionsPanel = new JPanel();
        quitGameButton = new JButton();
        nextHandButton = new JButton();
        dealButton = new JButton();
        handOptionsLabel = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Blackjack");
        setExtendedState(Frame.MAXIMIZED_BOTH);
        setIconImage(new ImageIcon(getClass().getResource(
            "/blackjack/images/logo2.png"
        )).getImage());

        betOptionsPanel.setBackground(new Color(19, 19, 19));

        betButton1.setBackground(new Color(26, 26, 26));
        betButton1.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        betButton1.setForeground(new Color(255, 255, 255));
        betButton1.setText("5");
        betButton1.setFocusPainted(false);

        betButton2.setBackground(new Color(26, 26, 26));
        betButton2.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        betButton2.setForeground(new Color(255, 255, 255));
        betButton2.setText("10");
        betButton2.setFocusPainted(false);

        betButton3.setBackground(new Color(26, 26, 26));
        betButton3.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        betButton3.setForeground(new Color(255, 255, 255));
        betButton3.setText("25");
        betButton3.setFocusPainted(false);

        betButton4.setBackground(new Color(26, 26, 26));
        betButton4.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        betButton4.setForeground(new Color(255, 255, 255));
        betButton4.setText("50");
        betButton4.setFocusPainted(false);

        betOptionsLabel.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        betOptionsLabel.setForeground(new Color(255, 255, 255));
        betOptionsLabel.setText("Bet");

        betButton5.setBackground(new Color(26, 26, 26));
        betButton5.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        betButton5.setForeground(new Color(255, 255, 255));
        betButton5.setText("100");
        betButton5.setFocusPainted(false);

        GroupLayout betOptionsPanelLayout = new GroupLayout(betOptionsPanel);
        betOptionsPanel.setLayout(betOptionsPanelLayout);
        betOptionsPanelLayout.setHorizontalGroup(betOptionsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(betOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(betOptionsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(betOptionsPanelLayout.createSequentialGroup()
                        .addComponent(betOptionsLabel)
                        .addGap(74, 74, 74))
                    .addGroup(betOptionsPanelLayout.createSequentialGroup()
                        .addComponent(betButton1, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(betButton2)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(betButton3)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(betButton4)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(betButton5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        betOptionsPanelLayout.setVerticalGroup(betOptionsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(betOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(betOptionsLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(betOptionsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(betButton1)
                    .addComponent(betButton2)
                    .addComponent(betButton3)
                    .addComponent(betButton4)
                    .addComponent(betButton5))
                .addContainerGap())
        );

        currentBetPanel.setBackground(new Color(19, 19, 19));

        currentBetValueLabel.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
        currentBetValueLabel.setForeground(new Color(255, 255, 255));
        currentBetValueLabel.setText("0");

        currentBetLabel.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
        currentBetLabel.setForeground(new Color(255, 255, 255));
        currentBetLabel.setText("Bet:");

        GroupLayout currentBetPanelLayout = new GroupLayout(currentBetPanel);
        currentBetPanel.setLayout(currentBetPanelLayout);
        currentBetPanelLayout.setHorizontalGroup(currentBetPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(currentBetPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(currentBetLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentBetValueLabel)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        currentBetPanelLayout.setVerticalGroup(currentBetPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, currentBetPanelLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(currentBetPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(currentBetValueLabel)
                    .addComponent(currentBetLabel))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablePanel.setBackground(new Color(0, 102, 51));

        titleLabel.setFont(new Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setForeground(new Color(255, 255, 255));
        titleLabel.setText("BLACKJACK");

        dealerPanel.setBackground(new Color(0, 102, 51));

        dealerCardLabel1.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        dealerCardLabel1.setText("Empty");

        dealerCardLabel2.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        dealerCardLabel2.setText("Empty");

        dealerCardLabel3.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        dealerCardLabel3.setText("Empty");

        dealerCardLabel4.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        dealerCardLabel4.setText("Empty");

        dealerCardLabel5.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        dealerCardLabel5.setText("Empty");

        dealerCardLabel6.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        dealerCardLabel6.setText("Empty");

        dealerCardLabel7.setText("jLabel6");

        dealerCardLabel8.setText("jLabel7");

        dealerCardLabel9.setText("jLabel8");

        dealerCardLabel10.setText("jLabel9");

        dealerCardLabel11.setText("jLabel10");

        GroupLayout dealerPanelLayout = new GroupLayout(dealerPanel);
        dealerPanel.setLayout(dealerPanelLayout);
        dealerPanelLayout.setHorizontalGroup(dealerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(dealerPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(dealerCardLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dealerCardLabel2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dealerCardLabel3)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dealerCardLabel4)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dealerCardLabel5)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dealerCardLabel6)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dealerCardLabel7)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dealerCardLabel8)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dealerCardLabel9)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dealerCardLabel10)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dealerCardLabel11)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dealerPanelLayout.setVerticalGroup(dealerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(dealerPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(dealerPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(dealerCardLabel1)
                    .addComponent(dealerCardLabel2)
                    .addComponent(dealerCardLabel3)
                    .addComponent(dealerCardLabel4)
                    .addComponent(dealerCardLabel5)
                    .addComponent(dealerCardLabel6)
                    .addComponent(dealerCardLabel7)
                    .addComponent(dealerCardLabel8)
                    .addComponent(dealerCardLabel9)
                    .addComponent(dealerCardLabel10)
                    .addComponent(dealerCardLabel11))
                .addGap(20, 20, 20))
        );

        dealerHandValueLabel.setFont(new Font("Segoe UI", 0, 16)); // NOI18N
        dealerHandValueLabel.setForeground(new Color(255, 255, 255));
        dealerHandValueLabel.setText("Dealer");
        dealerHandValueLabel.setToolTipText("");

        chipsLabel.setFont(new Font("Segoe UI", 0, 36)); // NOI18N
        chipsLabel.setForeground(new Color(255, 255, 255));
        chipsLabel.setText("0");

        playerPanel.setBackground(new Color(0, 102, 51));

        playerCardLabel1.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        playerCardLabel1.setText("Empty");

        playerCardLabel2.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        playerCardLabel2.setText("Empty");

        playerCardLabel3.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        playerCardLabel3.setText("Empty");

        playerCardLabel4.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        playerCardLabel4.setText("Empty");

        playerCardLabel5.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        playerCardLabel5.setText("Empty");

        playerCardLabel6.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        playerCardLabel6.setText("Empty");

        playerCardLabel7.setText("jLabel1");

        playerCardLabel8.setText("jLabel2");

        playerCardLabel9.setText("jLabel3");

        playerCardLabel10.setText("jLabel4");

        playerCardLabel11.setText("jLabel5");

        GroupLayout playerPanelLayout = new GroupLayout(playerPanel);
        playerPanel.setLayout(playerPanelLayout);
        playerPanelLayout.setHorizontalGroup(playerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(playerPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(playerCardLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(playerCardLabel2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(playerCardLabel3)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(playerCardLabel4)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(playerCardLabel5)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(playerCardLabel6)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(playerCardLabel7)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(playerCardLabel8)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(playerCardLabel9)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(playerCardLabel10)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(playerCardLabel11)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        playerPanelLayout.setVerticalGroup(playerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(playerPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(playerPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(playerCardLabel1)
                    .addComponent(playerCardLabel2)
                    .addComponent(playerCardLabel3)
                    .addComponent(playerCardLabel4)
                    .addComponent(playerCardLabel5)
                    .addComponent(playerCardLabel6)
                    .addComponent(playerCardLabel7)
                    .addComponent(playerCardLabel8)
                    .addComponent(playerCardLabel9)
                    .addComponent(playerCardLabel10)
                    .addComponent(playerCardLabel11))
                .addGap(20, 20, 20))
        );

        playerHandValueLabel.setFont(new Font("Segoe UI", 0, 16)); // NOI18N
        playerHandValueLabel.setForeground(new Color(255, 255, 255));
        playerHandValueLabel.setText("Player (0)");

        messagePanel.setBackground(tablePanel.getBackground().darker());

        messageLabel.setFont(new Font("Segoe UI", 0, 16)); // NOI18N
        messageLabel.setForeground(new Color(255, 255, 255));
        messageLabel.setText("Welcome to Blackjack! Place your bet.");

        GroupLayout messagePanelLayout = new GroupLayout(messagePanel);
        messagePanel.setLayout(messagePanelLayout);
        messagePanelLayout.setHorizontalGroup(messagePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(messagePanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(messageLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        messagePanelLayout.setVerticalGroup(messagePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(messagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageLabel)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GroupLayout tablePanelLayout = new GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(tablePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tablePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(dealerPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tablePanelLayout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(messagePanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chipsLabel))
                    .addComponent(playerPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dealerHandValueLabel)
                    .addComponent(playerHandValueLabel))
                .addContainerGap())
        );
        tablePanelLayout.setVerticalGroup(tablePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addGroup(tablePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(tablePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleLabel))
                    .addComponent(messagePanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(chipsLabel))
                .addGap(18, 18, 18)
                .addComponent(dealerHandValueLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dealerPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(playerHandValueLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        playOptionsPanel.setBackground(new Color(19, 19, 19));

        hitButton.setBackground(new Color(26, 26, 26));
        hitButton.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        hitButton.setForeground(new Color(255, 255, 255));
        hitButton.setText("Hit");
        hitButton.setFocusPainted(false);
        hitButton.setEnabled(false);

        standButton.setBackground(new Color(26, 26, 26));
        standButton.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        standButton.setForeground(new Color(255, 255, 255));
        standButton.setText("Stand");
        standButton.setFocusPainted(false);
        standButton.setEnabled(false);

        surrenderButton.setBackground(new Color(26, 26, 26));
        surrenderButton.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        surrenderButton.setForeground(new Color(255, 255, 255));
        surrenderButton.setText("Surrender");
        surrenderButton.setFocusPainted(false);
        surrenderButton.setEnabled(false);

        doubleDownButton.setBackground(new Color(26, 26, 26));
        doubleDownButton.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        doubleDownButton.setForeground(new Color(255, 255, 255));
        doubleDownButton.setText("Double Down");
        doubleDownButton.setFocusPainted(false);
        doubleDownButton.setEnabled(false);

        playOptionsLabel.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        playOptionsLabel.setForeground(new Color(255, 255, 255));
        playOptionsLabel.setText("Play");

        GroupLayout playOptionsPanelLayout = new GroupLayout(playOptionsPanel);
        playOptionsPanel.setLayout(playOptionsPanelLayout);
        playOptionsPanelLayout.setHorizontalGroup(playOptionsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(playOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(playOptionsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(playOptionsPanelLayout.createSequentialGroup()
                        .addComponent(hitButton)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(standButton)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doubleDownButton)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(surrenderButton))
                    .addComponent(playOptionsLabel))
                .addContainerGap())
        );
        playOptionsPanelLayout.setVerticalGroup(playOptionsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, playOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playOptionsLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(playOptionsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(hitButton, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(standButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(playOptionsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(doubleDownButton)
                        .addComponent(surrenderButton)))
                .addContainerGap())
        );

        handOptionsPanel.setBackground(new Color(19, 19, 19));

        quitGameButton.setBackground(new Color(26, 26, 26));
        quitGameButton.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        quitGameButton.setForeground(new Color(255, 255, 255));
        quitGameButton.setText("Quit Game");
        quitGameButton.setFocusPainted(false);

        nextHandButton.setBackground(new Color(26, 26, 26));
        nextHandButton.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        nextHandButton.setForeground(new Color(255, 255, 255));
        nextHandButton.setText("Next Hand");
        nextHandButton.setFocusPainted(false);
        nextHandButton.setEnabled(false);

        dealButton.setBackground(new Color(26, 26, 26));
        dealButton.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        dealButton.setForeground(new Color(255, 255, 255));
        dealButton.setText("Deal");
        dealButton.setFocusPainted(false);
        dealButton.setEnabled(false);

        handOptionsLabel.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        handOptionsLabel.setForeground(new Color(255, 255, 255));
        handOptionsLabel.setText("Hand");

        GroupLayout handOptionsPanelLayout = new GroupLayout(handOptionsPanel);
        handOptionsPanel.setLayout(handOptionsPanelLayout);
        handOptionsPanelLayout.setHorizontalGroup(handOptionsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(handOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(handOptionsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(handOptionsPanelLayout.createSequentialGroup()
                        .addComponent(dealButton, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextHandButton)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quitGameButton))
                    .addComponent(handOptionsLabel))
                .addContainerGap())
        );
        handOptionsPanelLayout.setVerticalGroup(handOptionsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, handOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(handOptionsLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(handOptionsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(dealButton)
                    .addComponent(nextHandButton)
                    .addComponent(quitGameButton))
                .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(currentBetPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(betOptionsPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(playOptionsPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(handOptionsPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(tablePanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tablePanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addComponent(betOptionsPanel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(handOptionsPanel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playOptionsPanel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currentBetPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void updateBetOptions(double chips) {
        final int[] BET_VALUES = {5, 10, 25, 50, 100};
        for (int i = 0, len = BET_VALUES.length; i < len; i++) {
            if (chips < BET_VALUES[i]) {
                betOptions[i].setEnabled(false);
            } else if (!betOptions[i].isEnabled()) {
                betOptions[i].setEnabled(true);
            }
        }
    }

    private void updateImages(ArrayList<Card> hand, JLabel[] labels) {
        try {
            int i = 0;
            for (Card card : hand) {
                labels[i].setIcon(card.getFrontIcon());
                i++;
            }
        } catch (IndexOutOfBoundsException ex) {
            ex.getMessage();
            disablePlayOption("Hit");
        }
    }

    public void updateCards(ArrayList<Card> playerHand, ArrayList<Card> dealerHand) {
        updateImages(playerHand, this.playerHand);
        updateImages(dealerHand, this.dealerHand);
    }

    public void updatePlayerHandValue(int playerHandValue) {
        playerHandValueLabel.setText(
                "Player ("
                + String.valueOf(playerHandValue)
                + ")"
        );
        dealerHandValueLabel.setText("Dealer");
    }

    public void updateDealerHandValue(int dealerHandValue) {
        dealerHandValueLabel.setText(
                "Dealer ("
                + String.valueOf(dealerHandValue)
                + ")"
        );
    }

    public void displayTableBorder() {
        playerPanel.setBorder(
            javax.swing.BorderFactory.createLineBorder(
                tablePanel.getBackground().brighter(), 5
            )
        );

        dealerPanel.setBorder(
            javax.swing.BorderFactory.createLineBorder(
                tablePanel.getBackground().brighter(), 5
            )
        );
    }

    public void clearHandValue() {
        playerHandValueLabel.setText("");
        dealerHandValueLabel.setText("");
    }

    public void clearMessage() {
        messageLabel.setText("");
        if (messagePanel.isOpaque()) {
            messagePanel.setOpaque(false);
        }
    }

    public void clearTableBorder() {
        playerPanel.setBorder(BorderFactory.createEmptyBorder());
        dealerPanel.setBorder(BorderFactory.createEmptyBorder());
    }

    public void updateStats(double chips, double bet) {
        chipsLabel.setText(Format.currency(chips));
        currentBetValueLabel.setText(Format.currency(bet));
    }

    public void initBetOptions(int[] betValues) {
        for (int i = 0; i < betOptions.length; i++) {
            betOptions[i].setText(String.valueOf(betValues[i]));
            betOptions[i].setIcon(ImageResizer.getScaledImage(
                    new ImageIcon(getClass().getResource(
                            "/blackjack/images/" + betValues[i] + ".png"
                    )),
                    betOptions[i].getFont().getSize()
            ));
            betOptions[i].setForeground(Color.WHITE);
            betOptions[i].setBackground(
                    betOptionsPanel.getBackground().darker()
            );
            betOptions[i].setFont(new Font(FONT_NAME, 0, 14));
        }
    }

    public void enablePlayOption(String option) {
        playOptions.get(option).setEnabled(true);
    }

    public void disablePlayOption(String option) {
        playOptions.get(option).setEnabled(false);
    }

    public void enableHandOption(String option) {
        handOptions.get(option).setEnabled(true);
    }

    public void disableHandOption(String option) {
        if (handOptions.containsKey(option)) {
            handOptions.get(option).setEnabled(false);
        }
    }

    public void enableAllPlayOptions() {
        playOptionsPanel.setVisible(true);
        playOptions.values().forEach((playOption) -> {
            playOption.setEnabled(true);
        });
    }

    public void disableAllPlayOptions() {
        // playOptionsPanel.setVisible(false);
        playOptions.values().forEach((playOption) -> {
            playOption.setEnabled(false);
        });
    }

    public void enableAllBetOptions() {
        // betOptionsPanel.setVisible(true);
        for (JButton betOption : betOptions) {
            betOption.setEnabled(true);
        }
    }

    public void disableAllBetOptions() {
        // betOptionsPanel.setVisible(false);
        for (JButton betOption : betOptions) {
            betOption.setEnabled(false);
        }
    }

    public void displayFrame() {
        setVisible(true);
    }

    public void displayMessage(String message, Color color) {
        if (!messagePanel.isVisible()) {
            messagePanel.setVisible(true);
        }
        if (!messagePanel.isOpaque()) {
            messagePanel.setOpaque(true);
        }
        if (!color.equals(messagePanel.getBackground())) {
            messagePanel.setBackground(color);
        }
        if (!message.equals(messageLabel.getText())) {
            messageLabel.setText(message);
        }
        messageLabel.setForeground(color.equals(Color.green)
                ? Color.black : Color.white);
    }

    public void displayMessage(String message) {
        displayMessage(message, tablePanel.getBackground().darker());
    }

    public void hideHoleCard(Card card) {
        dealerHand[0].setIcon(card.getBackIcon());
    }

    public void revealHoleCard(Card card) {
        dealerHand[0].setIcon(card.getFrontIcon());
    }

    private void resetImages(JLabel[] playerHand) {
        for (JLabel card : playerHand) {
            card.setIcon(null);
        }
    }

    public void clearCards() {
        resetImages(playerHand);
        resetImages(dealerHand);
    }

    public JButton[] getBetOptions() {
        return betOptions;
    }

    public void initHitActionListener(ActionListener l) {
        hitButton.addActionListener(l);
    }

    public void initStandActionListener(ActionListener l) {
        standButton.addActionListener(l);
    }

    public void initDoubleDownActionListener(ActionListener l) {
        doubleDownButton.addActionListener(l);
    }

    public void initSurrenderActionListener(ActionListener l) {
        surrenderButton.addActionListener(l);
    }

    public void initDealActionListener(ActionListener l) {
        dealButton.addActionListener(l);
    }

    public void initNextHandActionListener(ActionListener l) {
        nextHandButton.addActionListener(l);
    }

    public void initQuitGameActionListener(ActionListener l) {
        quitGameButton.addActionListener(l);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton betButton1;
    private JButton betButton2;
    private JButton betButton3;
    private JButton betButton4;
    private JButton betButton5;
    private JLabel betOptionsLabel;
    private JPanel betOptionsPanel;
    private JLabel chipsLabel;
    private JLabel currentBetLabel;
    private JPanel currentBetPanel;
    private JLabel currentBetValueLabel;
    private JButton dealButton;
    private JLabel dealerCardLabel1;
    private JLabel dealerCardLabel10;
    private JLabel dealerCardLabel11;
    private JLabel dealerCardLabel2;
    private JLabel dealerCardLabel3;
    private JLabel dealerCardLabel4;
    private JLabel dealerCardLabel5;
    private JLabel dealerCardLabel6;
    private JLabel dealerCardLabel7;
    private JLabel dealerCardLabel8;
    private JLabel dealerCardLabel9;
    private JLabel dealerHandValueLabel;
    private JPanel dealerPanel;
    private JButton doubleDownButton;
    private JLabel handOptionsLabel;
    private JPanel handOptionsPanel;
    private JButton hitButton;
    private JLabel messageLabel;
    private JPanel messagePanel;
    private JButton nextHandButton;
    private JLabel playOptionsLabel;
    private JPanel playOptionsPanel;
    private JLabel playerCardLabel1;
    private JLabel playerCardLabel10;
    private JLabel playerCardLabel11;
    private JLabel playerCardLabel2;
    private JLabel playerCardLabel3;
    private JLabel playerCardLabel4;
    private JLabel playerCardLabel5;
    private JLabel playerCardLabel6;
    private JLabel playerCardLabel7;
    private JLabel playerCardLabel8;
    private JLabel playerCardLabel9;
    private JLabel playerHandValueLabel;
    private JPanel playerPanel;
    private JButton quitGameButton;
    private JButton standButton;
    private JButton surrenderButton;
    private JPanel tablePanel;
    private JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}