/**
 * A GUI implementation of blackjack in Swing for ITE-6102 final
 * 
 * @author Joshua Timothy E. Abad
 */

package blackjack;

import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.border.TitledBorder;

public class BlackjackGUI extends javax.swing.JFrame {

    private final Deck deck;
    private final UserPlayer player;
    private final Dealer dealer;
    private final int minimumBet;
    private final JLabel[] playerHand;
    private final JLabel[] dealerHand;
    private final JButton[] playOptions;
    private final JButton[] betOptions;
    /**
     * Creates new form BlackjackGUI
     */
    public BlackjackGUI() {
        deck = new Deck();
        player = new UserPlayer();
        dealer = new Dealer();
        minimumBet = 25;
        initComponents();

        playerHand = new JLabel[6];
        playerHand[0] = lbPlayerCard1;
        playerHand[1] = lbPlayerCard2;
        playerHand[2] = lbPlayerCard3;
        playerHand[3] = lbPlayerCard4;
        playerHand[4] = lbPlayerCard5;
        playerHand[5] = lbPlayerCard6;

        dealerHand = new JLabel[6];
        dealerHand[0] = lbDealerCard1;
        dealerHand[1] = lbDealerCard2;
        dealerHand[2] = lbDealerCard3;
        dealerHand[3] = lbDealerCard4;
        dealerHand[4] = lbDealerCard5;
        dealerHand[5] = lbDealerCard6;
        
        playOptions = new JButton[4];
        playOptions[0] = btnHit;
        playOptions[1] = btnStand;
        playOptions[2] = btnDoubleDown;
        playOptions[3] = btnSurrender;

        betOptions = new JButton[5];
        betOptions[0] = btn5Chips;
        betOptions[1] = btn10Chips;
        betOptions[2] = btn25Chips;
        betOptions[3] = btn50Chips;
        betOptions[4] = btn100Chips;

        drawHand();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn5Chips = new javax.swing.JButton();
        btn10Chips = new javax.swing.JButton();
        btn25Chips = new javax.swing.JButton();
        btn50Chips = new javax.swing.JButton();
        btn100Chips = new javax.swing.JButton();
        lbBet = new javax.swing.JLabel();
        btnHit = new javax.swing.JButton();
        btnStand = new javax.swing.JButton();
        btnDoubleDown = new javax.swing.JButton();
        btnSurrender = new javax.swing.JButton();
        btnDeal = new javax.swing.JButton();
        btnNextHand = new javax.swing.JButton();
        btnQuitGame = new javax.swing.JButton();
        pnlDealerHand = new javax.swing.JPanel();
        lbDealerCard1 = new javax.swing.JLabel();
        lbDealerCard2 = new javax.swing.JLabel();
        lbDealerCard3 = new javax.swing.JLabel();
        lbDealerCard4 = new javax.swing.JLabel();
        lbDealerCard5 = new javax.swing.JLabel();
        lbDealerCard6 = new javax.swing.JLabel();
        pnlPlayerHand = new javax.swing.JPanel();
        lbPlayerCard1 = new javax.swing.JLabel();
        lbPlayerCard2 = new javax.swing.JLabel();
        lbPlayerCard3 = new javax.swing.JLabel();
        lbPlayerCard4 = new javax.swing.JLabel();
        lbPlayerCard5 = new javax.swing.JLabel();
        lbPlayerCard6 = new javax.swing.JLabel();
        pnlMessage = new javax.swing.JPanel();
        lbMessage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbBetValue = new javax.swing.JLabel();
        lbCurrentBet = new javax.swing.JLabel();
        lbChipsValue = new javax.swing.JLabel();
        lbChips = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbDealerHand = new javax.swing.JLabel();
        lbPlayerHand = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Blackjack");
        setExtendedState(Frame.MAXIMIZED_BOTH);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn5Chips.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn5Chips.setText("5");
        btn5Chips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ChipsActionPerformed(evt);
            }
        });

        btn10Chips.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn10Chips.setText("10");
        btn10Chips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ChipsActionPerformed(evt);
            }
        });

        btn25Chips.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn25Chips.setText("25");
        btn25Chips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn25ChipsActionPerformed(evt);
            }
        });

        btn50Chips.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn50Chips.setText("50");
        btn50Chips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn50ChipsActionPerformed(evt);
            }
        });

        btn100Chips.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn100Chips.setText("100");
        btn100Chips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100ChipsActionPerformed(evt);
            }
        });

        lbBet.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbBet.setText("Bet");

        btnHit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHit.setText("Hit");
        btnHit.setEnabled(false);
        btnHit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitActionPerformed(evt);
            }
        });

        btnStand.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStand.setText("Stand");
        btnStand.setEnabled(false);
        btnStand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStandActionPerformed(evt);
            }
        });

        btnDoubleDown.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDoubleDown.setText("Double Down");
        btnDoubleDown.setEnabled(false);
        btnDoubleDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoubleDownActionPerformed(evt);
            }
        });

        btnSurrender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSurrender.setText("Surrender");
        btnSurrender.setEnabled(false);
        btnSurrender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSurrenderActionPerformed(evt);
            }
        });

        btnDeal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeal.setText("Deal");
        btnDeal.setEnabled(false);
        btnDeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDealActionPerformed(evt);
            }
        });

        btnNextHand.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNextHand.setText("Next Hand");
        btnNextHand.setEnabled(false);
        btnNextHand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextHandActionPerformed(evt);
            }
        });

        btnQuitGame.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuitGame.setText("Quit Game");
        btnQuitGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbBet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnDeal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNextHand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQuitGame)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn5Chips)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn10Chips)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn25Chips)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn50Chips)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn100Chips))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnHit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnStand)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDoubleDown)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSurrender)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn100Chips)
                    .addComponent(btn50Chips)
                    .addComponent(btn25Chips)
                    .addComponent(btn10Chips)
                    .addComponent(btn5Chips)
                    .addComponent(lbBet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnHit)
                    .addComponent(btnStand)
                    .addComponent(btnDoubleDown)
                    .addComponent(btnSurrender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeal)
                    .addComponent(btnNextHand)
                    .addComponent(btnQuitGame))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDealerHand.setBackground(new java.awt.Color(0, 102, 51));

        lbDealerCard1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDealerCard1.setText("Empty");

        lbDealerCard2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDealerCard2.setText("Empty");

        lbDealerCard3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDealerCard3.setText("Empty");

        lbDealerCard4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDealerCard4.setText("Empty");

        lbDealerCard5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDealerCard5.setText("Empty");

        lbDealerCard6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDealerCard6.setText("Empty");

        javax.swing.GroupLayout pnlDealerHandLayout = new javax.swing.GroupLayout(pnlDealerHand);
        pnlDealerHand.setLayout(pnlDealerHandLayout);
        pnlDealerHandLayout.setHorizontalGroup(
            pnlDealerHandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDealerHandLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lbDealerCard1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbDealerCard2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbDealerCard3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbDealerCard4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbDealerCard5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbDealerCard6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDealerHandLayout.setVerticalGroup(
            pnlDealerHandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDealerHandLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnlDealerHandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDealerCard1)
                    .addComponent(lbDealerCard2)
                    .addComponent(lbDealerCard3)
                    .addComponent(lbDealerCard4)
                    .addComponent(lbDealerCard5)
                    .addComponent(lbDealerCard6))
                .addGap(44, 44, 44))
        );

        pnlPlayerHand.setBackground(new java.awt.Color(0, 102, 51));

        lbPlayerCard1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbPlayerCard1.setText("Empty");

        lbPlayerCard2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbPlayerCard2.setText("Empty");

        lbPlayerCard3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbPlayerCard3.setText("Empty");

        lbPlayerCard4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbPlayerCard4.setText("Empty");

        lbPlayerCard5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbPlayerCard5.setText("Empty");

        lbPlayerCard6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbPlayerCard6.setText("Empty");

        javax.swing.GroupLayout pnlPlayerHandLayout = new javax.swing.GroupLayout(pnlPlayerHand);
        pnlPlayerHand.setLayout(pnlPlayerHandLayout);
        pnlPlayerHandLayout.setHorizontalGroup(
            pnlPlayerHandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlayerHandLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lbPlayerCard1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPlayerCard2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPlayerCard3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPlayerCard4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPlayerCard5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPlayerCard6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPlayerHandLayout.setVerticalGroup(
            pnlPlayerHandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlayerHandLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnlPlayerHandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPlayerCard1)
                    .addComponent(lbPlayerCard2)
                    .addComponent(lbPlayerCard3)
                    .addComponent(lbPlayerCard4)
                    .addComponent(lbPlayerCard5)
                    .addComponent(lbPlayerCard6))
                .addGap(44, 44, 44))
        );

        pnlMessage.setBackground(new java.awt.Color(153, 153, 153));
        pnlMessage.setOpaque(false);

        javax.swing.GroupLayout pnlMessageLayout = new javax.swing.GroupLayout(pnlMessage);
        pnlMessage.setLayout(pnlMessageLayout);
        pnlMessageLayout.setHorizontalGroup(
            pnlMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMessageLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbMessage)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pnlMessageLayout.setVerticalGroup(
            pnlMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMessageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMessage)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText(
            String.valueOf(this.minimumBet)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Minimum Bet:");

        lbBetValue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbBetValue.setText(String.valueOf(player.getBet())
        );

        lbCurrentBet.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbCurrentBet.setText("Bet:");

        lbChipsValue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbChipsValue.setText(String.valueOf(this.player.getChips()));

        lbChips.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbChips.setText("Chips:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCurrentBet)
                    .addComponent(lbChips)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbChipsValue)
                    .addComponent(lbBetValue)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbChips)
                        .addComponent(lbChipsValue))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbBetValue)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbCurrentBet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Futura LT", 1, 24)); // NOI18N
        jLabel3.setText("BLACKJACK");

        lbDealerHand.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDealerHand.setText("Dealer");
        lbDealerHand.setToolTipText("");

        lbPlayerHand.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbPlayerHand.setText("Player (0)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPlayerHand, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDealerHand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDealerHand)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPlayerHand)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbDealerHand)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDealerHand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPlayerHand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPlayerHand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn5ChipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ChipsActionPerformed
        bet(5);
    }//GEN-LAST:event_btn5ChipsActionPerformed

    private void btn10ChipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ChipsActionPerformed
        bet(10);
    }//GEN-LAST:event_btn10ChipsActionPerformed

    private void btn25ChipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn25ChipsActionPerformed
        bet(25);
    }//GEN-LAST:event_btn25ChipsActionPerformed

    private void btn50ChipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn50ChipsActionPerformed
        bet(50);
    }//GEN-LAST:event_btn50ChipsActionPerformed

    private void btn100ChipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100ChipsActionPerformed
        bet(100);
    }//GEN-LAST:event_btn100ChipsActionPerformed

    private void displayMessage(String message, Color color) {
        if (!pnlMessage.isVisible()) {
            pnlMessage.setVisible(true);
        }
        if (!pnlMessage.isOpaque()) {
            pnlMessage.setOpaque(true);
        }
        pnlMessage.setBackground(color);
        lbMessage.setText(message);
        lbMessage.setFont(new Font("Segoe UI", 1, 12));
    }

    private void displayMessage(String message) {
        displayMessage(message, new Color(153, 153, 153));
        if (pnlMessage.isOpaque()) {
            pnlMessage.setOpaque(false);
        }
    }

    private void clearMessage() {
        lbMessage.setText("");
        if (pnlMessage.isOpaque()) {
            pnlMessage.setOpaque(false);
        }
    }
   
    private void updateHandValue(Player player, JLabel playerLabel) {
        playerLabel.setText(player + " (" + player.stand() + ")");
    }

    private void btnHitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitActionPerformed
        Card card = deck.getCard();
        player.hit(card);

        displayMessage("You drew " + card);
        updateHandValue(player, lbPlayerHand);
        
        int i = 0;
        for (JLabel playerCard : playerHand) {
            if (playerCard.getText().equals("Empty")) {
                playerCard.setText(card.toString());
                if (i == 5) {
                    btnHit.setEnabled(false);
                    btnDoubleDown.setEnabled(false);
                }
                break;
            }
            i++;
        }
        
        if (player.stand() > 21) {
            btnHit.setEnabled(false);
            btnDoubleDown.setEnabled(false);
            btnSurrender.setEnabled(false);
        }
        drawHand();
    }//GEN-LAST:event_btnHitActionPerformed

    private void drawHand() {
        int i = 0;
        for (JLabel playerCard : playerHand) {
            if (playerCard.getText().equals("Empty")) {
                playerCard.setVisible(false);
            } else if (!playerCard.getText().equals("")) {
                playerCard.setIcon(player.getHand().get(i).frontIcon);
                playerCard.setText("");
                playerCard.setVisible(true);
            }
            i++;
        }

        i = 0;
        for (JLabel dealerCard : dealerHand) {
            if (dealerCard.getText().equals("Empty")) {
                dealerCard.setVisible(false);
            } else if (dealerCard.getText().equals("Hidden")) {
                dealerCard.setIcon(dealer.getHand().get(i).backIcon);
                dealerCard.setText("");
                dealerCard.setVisible(true);
            } else if (!dealerCard.getText().equals("")) {
                dealerCard.setIcon(dealer.getHand().get(i).frontIcon);
                dealerCard.setText("");
                dealerCard.setVisible(true);
            }
            i++;
        }
    } 
    private void btnSurrenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSurrenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSurrenderActionPerformed

    private void btnDealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDealActionPerformed
        setOptions(betOptions, false);

        setOptions(playOptions, true);
        if (player.getBet() * 2 > player.getChips()) {
            btnDoubleDown.setEnabled(false);
        }
        
        for (int i = 0; i < 2; i++) {
            Card playerCard = deck.getCard();
            Card dealerCard = deck.getCard();
            player.hit(playerCard);
            dealer.hit(dealerCard);
            if (i == 0) {
                lbPlayerCard1.setText(playerCard.toString());
                lbDealerCard1.setText("Hidden");
            } else {
                lbPlayerCard2.setText(playerCard.toString());
                lbDealerCard2.setText(dealerCard.toString());
            }
        }

        btnDeal.setEnabled(false);

        updateHandValue(player, lbPlayerHand);

        drawHand();
    }//GEN-LAST:event_btnDealActionPerformed

    private void btnQuitGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitGameActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnQuitGameActionPerformed

    private void setOptions(JButton[] options, boolean state) {
        for (JButton option : options) {
            if (option.isEnabled() != state) {
                option.setEnabled(state);
            }
        }
    }

    private void btnStandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStandActionPerformed
        setOptions(playOptions, false);
        pnlMessage.setVisible(true);
        lbDealerCard1.setText(dealer.getHand().get(0).toString());

        if (dealer.hasSoft17() || dealer.stand() <= 16) {
            Card card = deck.getCard();
            dealer.hit(card);
            for (JLabel cardLabel : dealerHand) {
                if (cardLabel.getText().equals("Empty")) {
                    cardLabel.setText(card.toString());
                    break;
                }
            }
        }
        drawHand();

        final int playerFinalHand = player.stand();
        final int dealerFinalHand = dealer.stand();

        updateHandValue(dealer, lbDealerHand);

        Player winner = null;
        if (player.isBelowLimit() && dealer.isBelowLimit()) {
            if (playerFinalHand == dealerFinalHand) {
                lbMessage.setText("Draw");
                player.addChips(player.getBet());
                player.setBet(0);
            } else {
                winner = playerFinalHand > dealerFinalHand ? player : dealer;
            }

        // If either the player or the dealer went past the limit, but not both
        } else if (playerFinalHand > 21 ^ dealerFinalHand > 21){
            winner = playerFinalHand <= 21 ? player : dealer;
        } else {
            displayMessage("You lost", Color.red);
        }

        if (winner != null) {
            if (winner instanceof Dealer) {
                displayMessage((dealer.hasBlackjack()) ? 
                    "The Dealer got blackjack" : "The Dealer won this round", 
                    Color.red);
            } else {
                displayMessage((player.hasBlackjack()) ? 
                    "You got blackjack" : "You won this round", 
                    Color.green);
                player.addChips(player.getBet() * 2);
            }
            player.setBet(0);
        }

        // End the game if the player is out of chips
        if (player.getChips() < minimumBet) {
            displayMessage("You lost the game", Color.red);
        } else {
            btnNextHand.setEnabled(true);
        }
        
        lbChipsValue.setText(String.valueOf(player.getChips()));
        lbBetValue.setText("0");
    }//GEN-LAST:event_btnStandActionPerformed

    private void btnNextHandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextHandActionPerformed
        for (JLabel cardLabel : playerHand) {
            cardLabel.setText("Empty");
        }

        for (JLabel cardLabel : dealerHand) {
            cardLabel.setText("Empty");
        }

        updateBetOptions();

        clearMessage();
        btnNextHand.setEnabled(false);
        player.resetHand(this.deck);
        dealer.resetHand(this.deck);

        updateHandValue(player, lbPlayerHand);
        updateHandValue(dealer, lbDealerHand);

        drawHand();
    }//GEN-LAST:event_btnNextHandActionPerformed

    private void btnDoubleDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoubleDownActionPerformed
        // TODO add your handling code here:
        player.doubleBet();
        Card card = deck.getCard();
        player.hit(card);

        displayMessage("You drew " + card);
        updateHandValue(player, lbPlayerHand);
        
        int i = 0;
        for (JLabel playerCard : playerHand) {
            if (playerCard.getText().equals("Empty")) {
                playerCard.setText(card.toString());
                if (i == 5) {
                    btnHit.setEnabled(false);
                    btnDoubleDown.setEnabled(false);
                }
                break;
            }
            i++;
        }
        
        lbBetValue.setText(String.valueOf(player.getBet()));
        lbChipsValue.setText(String.valueOf(player.getChips()));
        btnHit.setEnabled(false);
        btnDoubleDown.setEnabled(false);
        btnSurrender.setEnabled(false);
        drawHand();
    }//GEN-LAST:event_btnDoubleDownActionPerformed

    private void bet(int amount) {
        if (player.getBet() == 0) {
            player.setBet(amount);
        } else {
            player.addBet(amount);
        }
        lbBetValue.setText(String.valueOf(player.getBet()));
        lbChipsValue.setText(String.valueOf(player.getChips()));
        if (player.getBet() >= minimumBet) {
            btnDeal.setEnabled(true);
        }

        updateBetOptions();
    }

    private void updateBetOptions() {
        final int[] BET_VALUES = {5, 10, 25, 50, 100};
        for (int i = 0, len = BET_VALUES.length; i < len; i++) {
            if (player.getChips() < BET_VALUES[i]) {
                betOptions[i].setEnabled(false);
            } else if (!betOptions[i].isEnabled()) {
                betOptions[i].setEnabled(true);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlackjackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlackjackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlackjackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlackjackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlackjackGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn100Chips;
    private javax.swing.JButton btn10Chips;
    private javax.swing.JButton btn25Chips;
    private javax.swing.JButton btn50Chips;
    private javax.swing.JButton btn5Chips;
    private javax.swing.JButton btnDeal;
    private javax.swing.JButton btnDoubleDown;
    private javax.swing.JButton btnHit;
    private javax.swing.JButton btnNextHand;
    private javax.swing.JButton btnQuitGame;
    private javax.swing.JButton btnStand;
    private javax.swing.JButton btnSurrender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbBet;
    private javax.swing.JLabel lbBetValue;
    private javax.swing.JLabel lbChips;
    private javax.swing.JLabel lbChipsValue;
    private javax.swing.JLabel lbCurrentBet;
    private javax.swing.JLabel lbDealerCard1;
    private javax.swing.JLabel lbDealerCard2;
    private javax.swing.JLabel lbDealerCard3;
    private javax.swing.JLabel lbDealerCard4;
    private javax.swing.JLabel lbDealerCard5;
    private javax.swing.JLabel lbDealerCard6;
    private javax.swing.JLabel lbDealerHand;
    private javax.swing.JLabel lbMessage;
    private javax.swing.JLabel lbPlayerCard1;
    private javax.swing.JLabel lbPlayerCard2;
    private javax.swing.JLabel lbPlayerCard3;
    private javax.swing.JLabel lbPlayerCard4;
    private javax.swing.JLabel lbPlayerCard5;
    private javax.swing.JLabel lbPlayerCard6;
    private javax.swing.JLabel lbPlayerHand;
    private javax.swing.JPanel pnlDealerHand;
    private javax.swing.JPanel pnlMessage;
    private javax.swing.JPanel pnlPlayerHand;
    // End of variables declaration//GEN-END:variables
}
